### ISSUE TITLE
some errors in. libc/arch-arm64/generic/bionic/strrchr.S

### ISSUE THREAD

**Issue by karthick111** [CarbonROM/android_bionic#1]
Need this to get solved 
https://github.com/CyanogenMod/android_bionic/commit/e87a5b3d6fd488965c3c8927816db70497e88e65

**Comment by imrasalghul** [comment]
ty 👍

**Comment by imrasalghul** [comment]
Will be fixed. :)

**Comment by Myself5** [comment]
@karthick111 you could send in the commit for the respective branch to our gerrit (http://review.carbonrom.org/) ;)
Else, you'd need to tell me what branch you get the errors on, and what specific errors they are please, so I can look into them.

EDIT: Be sure to tag me on it ;)

**Comment by karthick111** [comment]
cr-4.0 branch 
Oh thanks
Haven't noticed that carbon have gerrit
